# USDExportPlugin
# Initial code generated by Softimage SDK Wizard
# Executed Mon May 4 17:54:03 UTC+0500 2020 by Shekn
#
# Tip: To add a command to this plug-in, right-click in the
# script editor and choose Tools > Add Command.
import win32com.client
from win32com.client import constants
import sys
if __sipath__ not in sys.path:
    sys.path.append(__sipath__)
import import_processor
import imp

null = None
false = 0
true = 1
app = Application


def log(message):
    app.LogMessage(message)


def XSILoadPlugin(in_reg):
    in_reg.Author = "Shekn"
    in_reg.Name = "USDImportPlugin"
    in_reg.Major = 1
    in_reg.Minor = 0

    in_reg.RegisterCommand("USDImport", "USDImport")
    in_reg.RegisterCommand("USDImportOpen", "USDImportOpen")
    # RegistrationInsertionPoint - do not remove this line

    return true


def XSIUnloadPlugin(in_reg):
    strPluginName = in_reg.Name
    app.LogMessage(str(strPluginName) + str(" has been unloaded."), constants.siVerbose)
    return true


def USDImport_Init(in_ctxt):
    command = in_ctxt.Source
    args = command.Arguments
    # init parameters of the command
    args.Add("file_path")

    return True


def USDImport_Execute(*args):
    app.LogMessage("USDImport_Execute called", constants.siVerbose)
    # read arguments of the command
    file_path = args[0]

    imp.reload(import_processor)
    import_processor.import_usd(app, "D:\\Graphic\\For Softimage\\Projects\\USD Development\\Models\\test.usda")

    return True


def USDImportOpen_Execute():
    scene_root = app.ActiveProject2.ActiveScene.Root

    # create property
    prop = scene_root.AddProperty("CustomProperty", False, "USD_Import")

    # add parameters
    prop.AddParameter3("file_path", constants.siString, "", "", "", False, False)

    # define layout
    layout = prop.PPGLayout
    layout.Clear()
    item = layout.AddItem("file_path", "File", constants.siControlFilePath)
    item.SetAttribute(constants.siUIOpenFile, True)
    item.SetAttribute(constants.siUIFileMustExist, False)
    filter_string = "USD files (*.usd *.usdc *.usda *.usdz)|*.usd:*.usdc:*.usda:*.usdz|"
    item.SetAttribute(constants.siUIFileFilter, filter_string)
    rtn = app.InspectObj(prop, "", "Import *.usd file...", constants.siModal, False)
    if rtn is False:
        # click "ok", execute import command
        app.USDImport(prop.Parameters("file_path").Value)

    # delete dialog
    app.DeleteObj(prop)

    return True
